### PR TITLE
Beth Sudkamp - debug python nullspace code

### PR DESCRIPTION
**Pull request by esudkamp**
I think this should fix the errors in python; but i can't double chec…k it to make sure since the version of the makefile I have checked out keeps saying that there is syntax near unexpected token `fi' on line 16963.

### CODE REVIEW

**Comment by ofloveandhate** [comment]
your indentation changes mine from tabs to spaces.  will you please change your indentation from spaces to tabs?

**Comment by ofloveandhate** [comment]
also, you really need to be able to check the correctness before PR'ing.  

this `unexpected token` nonsense rears its ugly head again...  can you send me a compressed file of your repo, by email?  then, i will unpack it in cygwin, and replicate and fix that stupid problem.

**Comment by esudkamp** [comment]
|  
|    |  
bertini_real.zip
 Zip via Dropbox  |  |

  |

 
Here is the compressed copy of my repo. I will work on the tabs and get that fixed. 
Beth    On Friday, January 20, 2017 12:34 PM, dani brake <notifications@github.com> wrote:
 

 also, you really need to be able to check the correctness before PR'ing.this unexpected token nonsense rears its ugly head again... can you send me a compressed file of your repo, by email? then, i will unpack it in cygwin, and replicate and fix that stupid problem.—

**Comment by ofloveandhate** [comment]
this pull request does not resolve the issue i was talking about, and creates some new ones.  i think i should elaborate on the difference between the outputs of the two deflation methods.

to see the difference, run the whitney example, using matlab and python.  the denominators of the determinantal functions is different:

```
diff -y singcurve_matlab singcurve_python 
CONFIG								CONFIG
randomseed: 0;							randomseed: 0;
endgamenum: 2;							endgamenum: 2;
imagthreshold: 1e-5;						imagthreshold: 1e-5;
sharpendigits: 30;						sharpendigits: 30;
tracktype: 1;							tracktype: 1;
securitymaxnorm: 1e6;						securitymaxnorm: 1e6;
END;								END;
INPUT								INPUT
variable_group x,y,z;						variable_group x,y,z;
function f1;							function f1;
f1=x^2-y^2*z;							f1=x^2-y^2*z;
function f_1_1,f_1_2,f_1_3;				      |	function f_1_1, f_1_2, f_1_3;
f_1_1 = (4*x)/3;					      |
f_1_2 = -(4*y*z)/3;					      |	f_1_1 = 4*x/9;
f_1_3 = -(2*y^2)/3;					      |	f_1_2 = -4*y*z/9;
							      >	f_1_3 = -2*y^2/9;
```

on the left with matlab, we get `3`, on the right with python, `9`

**Pull request closed without merging**
